### ISSUE TITLE
coinCode?

### ISSUE THREAD

**Issue by uekdyr** [Venthos/nodejs-pool#13]
Sorry if I'm being completely stupid here but can't seem to figure out why the pool says XMR instead of ITNS?

I've changed the coin in pools config.json, also updated it at the poolui (both globals.js & globals.default.js), updated the "coinCode" using the Admin panel but it still says XMR, is there any config that I'm missing or have I misunderstood the configs?

Cheers!

**Comment by Venthos** [comment]
You're not being stupid at all.  This is because poolui has "XMR" hard-coded throughout its entire codebase.  You can't just tweak a config and the UI will update on its own.  You would need to replace all instances of "XMR" manually or adjust them to use AngularJS to dynamically display the proper coin code.

**Comment by uekdyr** [comment]
Awesome, thanks!
