### ISSUE TITLE
Worker and Simplewallet issue

### ISSUE THREAD

**Issue by BKdilse** [Venthos/nodejs-pool#4]
I cannot see the RPC Wallet in the compiled intensecoin src, so I'm using simplewallet as follows:

/usr/local/src/intensecoin/build/release/src/simplewallet --rpc-bind-port 48783

Wallet is loaded, but the worker module cannot connect, error:
{"error":{"code":-32601,"message":"Method not found"},"id":"0","jsonrpc":"2.0"}
Unable to get wallet stats: Unable to get current wallet height

Any ideas?

**Comment by Venthos** [comment]
The fact that you see "simplewallet" at all means that you have built the older ByteCoin based version of Intense Coin instead of the newer Monero/XMR based version.

Did you use the deploy.bash script or manually set things up? The deploy script should automatically "checkout" the xmr branch and build from that latest release.

If you are using the older ByteCoin based version of Intense Coin intentionally, that's not a problem.  However, you will need to make sure your config.json is set to use "itns142" instead of "itns".  The "itns142" coin config is the one that supports the older 1.4.2 version of Intense Coin.  You will also need to use "walletd" as your wallet service instead of "simplewallet", as they have different JSON RPC methods (which is why you're getting "Method not found").

If you're starting off with a new pool, I would recommend the new XMR 1.44 codebase, though.

**Comment by BKdilse** [comment]
Thanks.  I ran the steps manually as I'm running things in screen rather than services.

I'm now recompiling with the checkout xmr bit.  Initially failed.  But now added cmake .  And it's progressing.

Thanks for speedy response.

**Comment by BKdilse** [comment]
Follow up, this worked out fine.  Took ages though, memory kept getting exhausted (server has 4GB), after numerous re-runs of make, it compiled, and pool is running.

Nice work @Venthos.

1 Question.  Do you know if XLC (Leviar coin) can be made to work on nodejs pool?  Any pointers in what I need to do to get it working, I don't mind giving it a go?

**Comment by Venthos** [comment]
Any Cryptonight/Cryptonight-Lite based coin should be workable in nodejs-pool.  It's a matter of creating a lib/coins/ and lib/payment_systems/ file for the coin that works with that coin's JSON RPC, since the JSON RPC can vary coin-to-coin.  Generally the coins seem to be more closely related to forknote/cryptonote (itns142.js is an example of this) or Monero (xmr.js of course being an example of that).  For the immediate future my focus is on improving the overall codebase (bug fixes/features) and ensuring Intense Coin support.  But I wouldn't rule it out at a later date.

**Comment by BKdilse** [comment]
OK thanks for that.
I like the way you're maintaining this repo, nice clear instructions and history, as it should be done. :)

**Comment by alexmateescu** [comment]
@BKdilse the height issue is a different implementation in the wallet. in the coin file search for getheight function and make it get_height and it will work.

**Comment by BKdilse** [comment]
Is this only for 1.42 or 1.44 as well?
I'm not seeing it in 1.44.

**Comment by Venthos** [comment]
itns142.js works with 'walletd' from ITNS 1.4.2 (Bytecoin based) repo.
itns.js works with 'intense-wallet-rpc' from ITNS 1.44 (XMR based) repo.

If you choose to use simplewallet, then none of the coin files are acceptable and will need changing.  I specifically avoided use of simplewallet because it requires passing the wallet password in clear text as an argument, a massive security risk.

**Comment by alexmateescu** [comment]
i have only worked with xao

it is in the xao.js file

**Comment by BKdilse** [comment]
That's fine, I'm using intense-wallet-rpc, so 1.44.  I don't need the height issue change do I?

**Comment by BKdilse** [comment]
I'm using itns, so ignore my question. It's working fine as is.
